title: "Docs"
metadataformat: "yaml"
# enableGitInfo so lastmod in sitemap.xml is based off git
enableGitInfo: false
canonifyURLs: true
pygmentsuseclasses: true
pygmentsCodeFences: true

publishDir: "./public"

# taxonomies
taxonomies:
  #tag: "tags"
  #category: "categories"
  "video-category": "video-categories"

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

# set this as a default otherwise we get "Error: found overlapping content dirs"
# contentDir: "content/en"

# gitinfo vars
enableGitInfo: true

# Allow to render HTML in markdown files
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true

# so we can access images as resources
# assetDir: "static"

module:
  imports:
    - path: "github.com/DataDog/websites-modules"
      disabled: false
      mounts:
      - source: layouts/partials/nav/main-nav.html
        target: layouts/partials/nav/main-nav.html
      - source: layouts/partials/nav/nav-logo-download.html
        target: layouts/partials/nav/nav-logo-download.html
      - source: layouts/partials/nav/menu-mobile.html
        target: layouts/partials/nav/menu-mobile.html
      - source: layouts/partials/announcement_banner.html
        target: layouts/partials/announcement_banner.html
      - source: assets/scss/base/_variables.scss
        target: assets/styles/base/_variables.scss
        path: src/styles/base/_variables.scss
      - source: assets/scss/components/_main-nav.scss
        target: assets/styles/components/_main-nav.scss
        path: src/styles/components/_main-nav.scss
      - source: assets/scss/components/_mobile-nav.scss
        target: assets/styles/components/_mobile-nav.scss
        path: src/styles/components/_mobile-nav.scss
      - source: assets/scss/base/_iconfont.scss
        target: assets/styles/components/_iconfont.scss
        path: src/styles/components/_iconfont.scss
      - source: static/fonts/icon-font/iconfont.eot
        target: static/fonts/iconfont.eot
      - source: static/fonts/icon-font/iconfont.ttf
        target: static/fonts/iconfont.ttf
      - source: static/fonts/icon-font/iconfont.svg
        target: static/fonts/iconfont.svg
      - source: static/fonts/icon-font/iconfont.woff
        target: static/fonts/iconfont.woff
      - source: assets/scss/components/_announcement-banner.scss
        target: assets/styles/components/_announcement-banner.scss
        path: src/styles/components/_announcement-banner.scss

  mounts:
    # default mounts
    - source: content/en
      target: content
      lang: en
    - source: content/fr
      target: content
      lang: fr
    - source: content/ja
      target: content
      lang: ja
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: static
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    # custom mounts
    - source: "./node_modules/@datadog/browser-rum/bundle/datadog-rum.js"
      target: "assets/node_modules/datadog-rum.js"
    - source: "./node_modules/@datadog/browser-logs/bundle/datadog-logs.js"
      target: "assets/node_modules/datadog-logs.js"
